# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/user_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protos/user_service.proto\x12\x04user\"F\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"%\n\x12\x43reateUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t2\x84\x01\n\x0bUserService\x12\x41\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x18.user.CreateUserResponse\"\x00\x12\x32\n\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.user_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATEUSERREQUEST']._serialized_start=35
  _globals['_CREATEUSERREQUEST']._serialized_end=105
  _globals['_CREATEUSERRESPONSE']._serialized_start=107
  _globals['_CREATEUSERRESPONSE']._serialized_end=144
  _globals['_LOGINREQUEST']._serialized_start=146
  _globals['_LOGINREQUEST']._serialized_end=196
  _globals['_LOGINRESPONSE']._serialized_start=198
  _globals['_LOGINRESPONSE']._serialized_end=228
  _globals['_USERSERVICE']._serialized_start=231
  _globals['_USERSERVICE']._serialized_end=363
# @@protoc_insertion_point(module_scope)
