version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: users-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Users
    ports:
      - 5432:5432
    volumes:
      - ./users/data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: users-cache
    restart: always
    ports:
      - 6379:6379
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: users-cache-insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - ./users/redisinsight:/db
  